// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "..\\..\\..\\..\\web\\src\\types\\Node";

/**
 * Connection with target node information
 */
export type ConnectionWithTarget = { id: string, label: string, order_index: number, target_node: Node, };