// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateConnection = { from_node_id: string, to_node_id: string, label: string, order_index: number, };