// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Connection } from "./Connection";
import type { Node } from "./Node";

/**
 * Complete graph for an issue category
 */
export type IssueGraph = { category: string, nodes: Array<Node>, connections: Array<Connection>, };