// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionWithTarget } from "./ConnectionWithTarget";
import type { Node } from "..\\..\\..\\..\\web\\src\\types\\Node";

/**
 * Node with its outgoing connections
 */
export type NodeWithConnections = { node: Node, connections: Array<ConnectionWithTarget>, };