// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateQuestion = { text: string | null, category: string | null, is_active: boolean | null, };