// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateConnection = { to_node_id: string | null, label: string | null, order_index: number | null, is_active: boolean | null, };