// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateNode = { text: string | null, semantic_id: string | null, position_x: number | null, position_y: number | null, is_active: boolean | null, };