// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiError } from "./ApiError";

/**
 * Standard error response format
 */
export type ErrorResponse = { error: ApiError, timestamp: string, };