// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Answer = { id: string, question_id: string, label: string, next_question_id: string | null, conclusion_text: string | null, order_index: number, is_active: boolean, created_at: string, updated_at: string, };