// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an answer leads to
 */
export type AnswerDestination = { type: string, question_id: string | null, question_text: string | null, conclusion_text: string | null, };