// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audit log entry
 */
export type AuditLogEntry = { id: bigint, timestamp: string, user_id: number | null, action: string, entity_type: string, entity_id: string, };