// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLogEntry } from "./AuditLogEntry";

/**
 * Response for audit logs list
 */
export type AuditLogsResponse = { logs: Array<AuditLogEntry>, total_count: bigint, page: number, page_size: number, };