// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CacheStats = { total_entries: number, active_entries: number, expired_entries: number, max_size: number, ttl_seconds: bigint, };