// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheStats } from "./CacheStats";

export type CacheMetrics = { questions_cache: CacheStats, issue_tree_cache: CacheStats, issue_graph_cache: CacheStats, };