// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Statistics by category
 */
export type CategoryStats = { category: string, count: bigint, };