// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRole } from "..\\..\\..\\api\\web\\src\\types\\UserRole";

/**
 * JWT Claims structure
 */
export type Claims = { 
/**
 * User ID
 */
sub: string, 
/**
 * User email
 */
email: string, 
/**
 * User role
 */
role: UserRole, 
/**
 * Issued at (Unix timestamp)
 */
iat: bigint, 
/**
 * Expiration time (Unix timestamp)
 */
exp: bigint, };