// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Statistics for a specific conclusion
 */
export type ConclusionStats = { conclusion: string, count: number, };