// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection data for export (with node array indices instead of UUIDs)
 */
export type ConnectionExportData = { 
/**
 * Index in nodes array (not UUID)
 */
from_node_index: number, 
/**
 * Index in nodes array (not UUID)
 */
to_node_index: number, label: string, order_index: number, };