// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateAnswer = { question_id: string, label: string, next_question_id: string | null, conclusion_text: string | null, order_index: number, };