// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new issue
 */
export type CreateIssueRequest = { name: string, category: string, display_category: string | null, root_question_text: string, };