// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryStats } from "./CategoryStats";
import type { ConclusionStats } from "./ConclusionStats";

/**
 * Dashboard statistics response
 */
export type DashboardStats = { total_sessions: number, completed_sessions: number, abandoned_sessions: number, active_sessions: number, avg_steps_to_completion: number, most_common_conclusions: Array<ConclusionStats>, sessions_by_category: Array<CategoryStats>, };