// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DatabaseMetrics = { pool_size: number, active_connections: number, idle_connections: number, };