// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for delete sessions endpoint
 */
export type DeleteSessionsResponse = { deleted_count: bigint, };