// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Answer } from "./Answer";
import type { Question } from "./Question";

/**
 * A step in the troubleshooting session history
 */
export type HistoryStep = { question: Question, answer: Answer, };