// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Answer } from "..\\..\\..\\api\\web\\src\\types\\Answer";
import type { Question } from "..\\..\\..\\api\\web\\src\\types\\Question";

/**
 * A step in the troubleshooting session history
 */
export type HistoryStep = { question: Question, answer: Answer, };