// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Connection } from "./Connection";
import type { Node } from "./Node";

/**
 * A step in the troubleshooting session history
 */
export type HistoryStep = { node: Node, connection: Connection, };