// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportError } from "./ImportError";
import type { ImportSuccess } from "./ImportSuccess";

/**
 * Result of importing issues
 */
export type ImportResult = { success: Array<ImportSuccess>, errors: Array<ImportError>, };