// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Successfully imported issue
 */
export type ImportSuccess = { category: string, name: string, nodes_count: number, connections_count: number, };