// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Issue represents a top-level troubleshooting category
 */
export type Issue = { id: string, name: string, category: string, display_category: string | null, root_question_id: string, is_active: boolean, question_count: bigint, created_at: string, updated_at: string, };