// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionExportData } from "./ConnectionExportData";
import type { IssueImportMetadata } from "./IssueImportMetadata";
import type { NodeExportData } from "./NodeExportData";

/**
 * Export data for a single issue (used for backup/restore)
 */
export type IssueExportData = { 
/**
 * Issue metadata for import
 */
issue: IssueImportMetadata, 
/**
 * All nodes in this issue category
 */
nodes: Array<NodeExportData>, 
/**
 * All connections between nodes
 */
connections: Array<ConnectionExportData>, };