// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Issue } from "./Issue";
import type { TreeNode } from "./TreeNode";

/**
 * Complete tree structure for an issue
 */
export type IssueTree = { issue: Issue, nodes: Array<TreeNode>, };