// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Issue metadata for import (without generated fields)
 */
export type IssueImportMetadata = { name: string, category: string, display_category: string | null, root_question_text: string, };