// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserInfo } from "./UserInfo";

/**
 * Login response with JWT token and user info
 */
export type LoginResponse = { token: string, user: UserInfo, };