// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Login request payload
 */
export type LoginRequest = { email: string, password: string, 
/**
 * If true, token will not expire. If false, token expires in 15 minutes.
 */
remember_me: boolean, };