// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Answer } from "./Answer";
import type { Question } from "./Question";

/**
 * Response for decision tree navigation
 */
export type NavigationResponse = { question: Question, answers: Array<Answer>, session_id: string, };