// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Navigation option (connection to next node)
 */
export type NavigationOption = { connection_id: string, label: string, target_category: string, display_category: string | null, };