// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Node data for export (with index references instead of UUIDs)
 */
export type NodeExportData = { node_type: string, text: string, semantic_id: string | null, position_x: number | null, position_y: number | null, };