// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheMetrics } from "./CacheMetrics";
import type { DatabaseMetrics } from "./DatabaseMetrics";

/**
 * Performance metrics response
 */
export type PerformanceMetrics = { database: DatabaseMetrics, cache: CacheMetrics, };