// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Answer } from "./Answer";

/**
 * Response for question with its answers
 */
export type QuestionWithAnswers = { id: string, semantic_id: string, text: string, category: string | null, answers: Array<Answer>, };