// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for renaming a category
 */
export type RenameCategoryRequest = { new_name: string, };