// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session summary for admin list view
 */
export type SessionSummary = { session_id: string, started_at: string, completed_at: string | null, abandoned: boolean, tech_identifier: string | null, client_site: string | null, final_conclusion: string | null, step_count: number, };