// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryStep } from "./HistoryStep";

/**
 * Response containing session history
 */
export type SessionHistoryResponse = { session_id: string, started_at: string, completed: boolean, steps: Array<HistoryStep>, final_conclusion: string | null, };