// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummary } from "./SessionSummary";

/**
 * Response for admin sessions list
 */
export type SessionsListResponse = { sessions: Array<SessionSummary>, total_count: bigint, page: number, page_size: number, };