// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to start a new troubleshooting session
 */
export type StartSessionRequest = { tech_identifier: string | null, client_site: string | null, category: string | null, };