// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavigationOption } from "./NavigationOption";
import type { Node } from "./Node";

/**
 * Response when starting a session (NODE-GRAPH VERSION)
 */
export type StartSessionResponse = { session_id: string, node: Node, options: Array<NavigationOption>, };