// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to submit an answer (NODE-GRAPH VERSION)
 */
export type SubmitAnswerRequest = { connection_id: string, };