// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavigationOption } from "./NavigationOption";
import type { Node } from "./Node";

/**
 * Response after submitting an answer (NODE-GRAPH VERSION)
 */
export type SubmitAnswerResponse = { session_id: string, node: Node, options: Array<NavigationOption>, is_conclusion: boolean, conclusion_text: string | null, };