// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Question } from "./Question";
import type { TreeAnswer } from "./TreeAnswer";

/**
 * Tree node representing a question and its branches
 */
export type TreeNode = { question: Question, answers: Array<TreeAnswer>, };