// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswerDestination } from "./AnswerDestination";

/**
 * Answer with its destination information
 */
export type TreeAnswer = { id: string, label: string, order_index: number, destination: AnswerDestination, };