// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update issue metadata
 */
export type UpdateIssueRequest = { name: string | null, display_category: string | null, is_active: boolean | null, };