// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAnswer = { label: string | null, next_question_id: string | null, conclusion_text: string | null, order_index: number | null, is_active: boolean | null, };