// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRole } from "..\\..\\..\\api\\web\\src\\types\\UserRole";

/**
 * User information returned in login response
 */
export type UserInfo = { id: string, email: string, role: UserRole, };